name: CI

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert[webpdf] playwright
          playwright install

      - name: Download data
        run: python src/download_data.py

      - name: Run backtest
        run: python src/mean_reversion_backtest.py

      - name: Execute notebook and export HTML
        run: jupyter nbconvert --execute --to html notebooks/mean_reversion_analysis.ipynb

      - name: Commit HTML report back to repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add notebooks/mean_reversion_analysis.html
          git commit -m "ci: update HTML report [skip ci]" || echo "No changes to commit"
          git push origin main
