name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_report:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装 Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. 安装依赖（含 notebook 导出所需）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert[webpdf]
          pip install playwright
          playwright install

      # 4. 运行回测脚本，确保不出错
      - name: Run backtest
        run: python src/mean_reversion_backtest.py

      # 5. 执行 notebook 并生成 HTML
      - name: Execute notebook and export HTML
        run: |
          jupyter nbconvert --execute --to html notebooks/mean_reversion_analysis.ipynb

      # 6. 保存 HTML 报告为构建产物
      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: html-report
          path: notebooks/mean_reversion_analysis.html
